### PR TITLE
Remove dependency on cabal-doctest

### LINKED ISSUE #37: Cannot install with Cabal 2.1
I am working on a project that requires features from the latest HEAD version of `Cabal` (see https://github.com/haskell/cabal/issues/4799). Something in my dependency tree pulled in `distributive` which caused my build to fail with this error:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for cabal-doctest-1.0.2:
    Cabal-2.1.0.0 must match >=1.10 && <2.1 (latest applicable is 2.0.0.2)
needed due to example-0.0.0 -> cabal-doctest-1.0.2

Plan construction failed.
```

This puzzled me because I wasn't trying to build tests for any of my dependencies. Why is `cabal-doctest` needed for `distributive`'s `Setup.lhs`? 

I ran into this problem with Stack 1.5.1. I assume the same thing happens with cabal-install. Here is a minimal way to reproduce the problem:

``` yaml
# stack.yaml
resolver: lts-9.0

packages:
  - .
  - extra-dep: true
    location:
      commit: 4009c986805cd2648a980d6e88f4c50a38a43410
      git: https://github.com/haskell/cabal
    subdirs:
      - Cabal

extra-deps:
  - distributive-0.5.3
```

``` yaml
# package.yaml
name: example
version: 0.0.0

library:
  dependencies:
    - Cabal
    - distributive
```

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #37. It also switches to the `lts-9.0` resolver because it wouldn't build with `nightly-2016-01-08`.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This will break the `doctest`s, and more importantly, this isn't the solution to the problem you're facing. See my comments [here](https://github.com/ekmett/distributive/issues/37#issuecomment-333140936).

**Comment by tfausak** [comment]
> This will break the doctests

Then the build might not be configured properly.

screen shot 2017-09-29 at 9 37 13 am

Regardless, the tests do fail for me locally. Fixing them is pretty easy:

``` diff
diff --git a/tests/doctests.hs b/tests/doctests.hs
index 2d080e7..1a136d7 100644
--- a/tests/doctests.hs
+++ b/tests/doctests.hs
@@ -13,13 +13,8 @@
 -----------------------------------------------------------------------------
 module Main where
 
-import Build_doctests (flags, pkgs, module_sources)
-import Data.Foldable (traverse_)
 import Test.DocTest
 
 main :: IO ()
 main = do
-    traverse_ putStrLn args
-    doctest args
-  where
-    args = flags ++ pkgs ++ module_sources
+    doctest ["src"]
```

I don't grok `cabal-doctest`. What does it do?

**Comment by RyanGlScott** [comment]
Indeed, I'm quite surprised that Travis is green there, since `cabal test` definitely failed [here](https://travis-ci.org/ekmett/distributive/jobs/281315462#L778).

In any case, I encourage reading [`cabal-doctest`'s README](https://github.com/phadej/cabal-doctest/blob/2d06fff4fae89ed22811e73e1121ca47f4e5ab34/README.md) for an overview of what it does. It solves many common pratfalls that can befall you when using `doctest` at scale. For example, if you have two packages installed that both define a module named `Foo` and attempt to import `Foo` somewhere in your project, then running `doctest` naked on your code will fail, since it won't be able to disambiguate between the two packages that provide `Foo`. The solution is to pass an explicit package ID an an argument to `doctest` to resolve the ambiguity, a tiresome task which `cabal-doctest` automates by gathering the appropriate info during the `configure` phase of `Cabal`.

Yes, it's quite annoying that all of this requires a custom `Setup` script to accomplish. There are [plans](https://github.com/haskell/cabal/issues/2327) to make `Cabal` aware of `doctest` in the future, so one day we will be able to axe this `Setup` shim entirely. But until them, we must do what we can.

As I said in https://github.com/ekmett/distributive/issues/37, the best solution to the particular problem you're facing (using `Cabal` HEAD) is to bump the upper version bounds on `Cabal` in `cabal-doctest` to allow it.

**Comment by tfausak** [comment]
I think the build succeeds because [the test script](https://github.com/ekmett/distributive/blob/24ea95d4b4c32bf59229ea67a7ef2f289a6c9258/.travis.yml#L123) just runs a bunch of commands without checking the exit codes. They would need to be joined by `&&` for the comment above them to be accurate. 

I did read `cabal-doctest`'s README, but it wasn't clear to me what it actually does. Thanks for explaining it. For this particular case, there's only a single doctest and it works fine without `cabal-doctest`. Is `cabal-doctest` really necessary here?

**Comment by RyanGlScott** [comment]
`cabal-doctest` isn't strictly necessary for testing `distributive` in isolation on Travis since the only packages we install are precisely its dependencies, so there's no worry of global module conflicts as described above. But there's no guarantee that this will hold if someone attempts to test `distributive` on their machine, which might have a substantially larger package database. Indeed, this is a problem that Stackage (which maintains an extraordinarily larges package database) has to deal with regularly. See [here](https://github.com/fpco/stackage/issues/2554) and [here](https://github.com/fpco/stackage/issues/2169) for examples of where this has bitten.

So yes, `cabal-doctest` is necessary to ensure that the tests will work reliably with different varieties of configurations.

**Pull request closed without merging**
