### PR TITLE
Setup.hs: Add compatibility with Cabal 1.25

### PR DESCRIPTION
**Pull request by bgamari**
Let's see whether this breaks anything.

### CODE REVIEW

**Comment by bgamari** [comment]
Oh, no Travis?

**Comment by RyanGlScott** [comment]
Hm, that is odd. Some things you can try:

1. Closing and re-opening the PR _might_ trick Travis into doing the right thing.
2. Alternatively, you can enable Travis on your fork of this repo, validate your changes on your fork, and post the results here.

**Comment by RyanGlScott** [comment]
Is this still needed? Or has this been superseded by https://github.com/haskell/cabal/pull/3939 (as you noted in https://github.com/ekmett/comonad/pull/38#issuecomment-251482270)?

**Comment by mitchellwrosen** [comment]
Hm, I'm not sure what I'm looking at in that issue. @bgamari could you explain how that's a better solution? I'm getting a build failure with distributive against Cabal 1.25 and this patch is exactly what I need.

Is it just that now's not a good time to try building against GHC head because some APIs are flux?

**Comment by phadej** [comment]
Made obsolete by #27

**Pull request closed without merging**
